# Generated by Django 6.0.4 on 2026-08-10 16:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartmind_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
