# Generated by Django 6.0.4 on 2026-07-16 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_user_admission_number_user_date_of_birth_and_more'),
        ('schools', '0002_alter_school_options_alter_schoolclass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_resources', models.BooleanField(default=True)),
                ('can_edit_resources', models.BooleanField(default=True)),
                ('can_delete_resources', models.BooleanField(default=False)),
                ('can_create_assignments', models.BooleanField(default=True)),
                ('can_mark_assignments', models.BooleanField(default=True)),
                ('can_create_quizzes', models.BooleanField(default=True)),
                ('can_mark_quizzes', models.BooleanField(default=True)),
                ('can_enter_marks', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_attendance', models.BooleanField(default=False)),
                ('can_manage_blog', models.BooleanField(default=False)),
                ('can_send_announcements', models.BooleanField(default=False)),
                ('can_manage_library', models.BooleanField(default=False)),
                ('can_manage_students', models.BooleanField(default=False)),
                ('can_manage_exams', models.BooleanField(default=False)),
                ('can_manage_timetable', models.BooleanField(default=False)),
                ('can_manage_fee_records', models.BooleanField(default=False)),
                ('can_manage_discipline', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_download_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['school_class', 'subject', 'teacher']},
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='schools.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, default='student', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='parentstudent',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'school_class', 'subject'), name='unique_teacher_assignment'),
        ),
        migrations.AddField(
            model_name='teacherpermission',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherrole',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_roles', to='schools.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='accounts.teacherrole'),
        ),
        migrations.AddConstraint(
            model_name='teacherrole',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_teacher_role_per_school'),
        ),
    ]
