# Generated by Django 6.0.4 on 2026-07-08 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('schools', '0002_alter_school_options_alter_schoolclass_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_school__ef3aa1_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='post',
            name='visible_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['school'], name='blog_post_school__9c211b_idx'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='grade',
        ),
    ]
