# Generated by Django 6.0.4 on 2026-09-26 16:39

import blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(storage=blog.storage.PostDocumentStorage(), upload_to=''),
        ),
    ]
