# Generated by Django 6.0.4 on 2026-07-09 18:38

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('assignments', '0001_initial'),
        ('schools', '0002_alter_school_options_alter_schoolclass_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.schoolclass'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.schoolclass'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school_class'], name='assignments_school__b0b612_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject'], name='assignments_subject_8f3bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher'], name='assignments_teacher_f24011_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_7a9bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student'], name='assignments_student_b7c7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['assignment'], name='assignments_assignm_b3d326_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student'], name='assignments_student_57ce54_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment'], name='assignments_assignm_684480_idx'),
        ),
    ]
