# Generated by Django 6.0.4 on 2026-07-27 05:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
