# Generated by Django 6.0.4 on 2026-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_question_option_a_alter_question_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
