# Generated by Django 6.0.4 on 2026-07-27 13:59

import assignments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_submission_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=assignments.storage.AssignmentStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=assignments.storage.SubmissionStorage(), upload_to=''),
        ),
    ]
