# Generated by Django 6.0.4 on 2026-09-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_alter_assignment_attachment_alter_submission_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
    ]
