# Generated by Django 6.0.4 on 2026-09-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional: explain why the correct answer is correct.', null=True),
        ),
    ]
