# Generated by Django 6.0.4 on 2026-09-18 21:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional: explain why the correct answer is correct.', null=True, verbose_name='Explanation'),
        ),
    ]
