# Generated by Django 6.0.4 on 2026-09-19 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_alter_question_explanation'),
        ('schools', '0002_alter_school_options_alter_schoolclass_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn'), ('CORRECTED', 'Corrected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school', 'status'], name='assignments_school__1e3c43_idx'),
        ),
        migrations.AddField(
            model_name='enrollmentaudit',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='assignments.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentaudit',
            name='new_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='enrollmentaudit',
            name='old_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='enrollmentaudit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enrollmentaudit',
            index=models.Index(fields=['enrollment', '-created_at'], name='assignments_enrollm_cdd465_idx'),
        ),
    ]
