# Generated by Django 6.0.4 on 2026-07-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='school',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='slogan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('junior_school', 'Junior School'), ('senior_school', 'Senior School')], default='junior_school', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Used to sort classes.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'name')},
        ),
    ]
